// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApiProject.DBContext;

#nullable disable

namespace TestApiProject.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20221030110356_SecondMigraton")]
    partial class SecondMigraton
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestApiProject.Models.ProductDetails", b =>
                {
                    b.Property<int>("slNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slNo"), 1L, 1);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("slNo");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            slNo = 101,
                            Price = 2000,
                            ProductDetail = "Operating System",
                            ProductName = "Windows OS",
                            ProductType = "Hardware"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
